import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const SUPABASE_URL="https://mxpbqyyunwfvvlccrmgv.supabase.co";
const SUPABASE_KEY=atob("c2JfcHVibGlzaGFibGVfaHRLOWpCLVIwd1I5X3BWRzhDTGV4UV9IbVR1S1lkSQ==");
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id); let mode="signin"; let profile=null; let pendingFactor=null;

const setTheme=t=>{document.body.classList.toggle("light",t==="light");$("theme").textContent=t==="light"?"Dark mode":"Light mode";localStorage.setItem("elitze-v2-theme",t)};
setTheme(localStorage.getItem("elitze-v2-theme")||"dark"); $("theme").onclick=()=>setTheme(document.body.classList.contains("light")?"dark":"light");

const dlg=$("dlg");
function authMode(next){mode=next;$("authtitle").textContent=next==="signup"?"Create account":next==="recovery"?"Reset password":"Sign in";$("submit").textContent=next==="signup"?"Create account":next==="recovery"?"Send reset email":"Sign in";$("extra").classList.toggle("hidden",next!=="signup");$("prow").classList.toggle("hidden",next==="recovery");$("apassword").required=next!=="recovery";document.querySelectorAll(".tab").forEach(b=>b.classList.remove("active"));$(next==="signup"?"t2":next==="recovery"?"t3":"t1").classList.add("active");$("authmsg").textContent=""}
function openAuth(m="signin"){authMode(m);dlg.showModal()}
$("auth").onclick=()=>openAuth();$("enter").onclick=()=>{if($("console").classList.contains("hidden"))openAuth();else $("console").scrollIntoView({behavior:"smooth"})};$("close").onclick=()=>dlg.close();$("t1").onclick=()=>openAuth();$("t2").onclick=()=>openAuth("signup");$("t3").onclick=()=>openAuth("recovery");

$("authform").onsubmit=async e=>{e.preventDefault();const email=$("aemail").value.trim().toLowerCase();$("authmsg").textContent="Processing…";try{
 if(mode==="signin"){const {error}=await supabase.auth.signInWithPassword({email,password:$("apassword").value});if(error)throw error;dlg.close()}
 else if(mode==="signup"){const redirect=location.href.split("#")[0];const meta={display_name:$("name").value.trim(),org_name:$("organization").value.trim()};let r=await supabase.auth.signUp({email,password:$("apassword").value,options:{data:meta,emailRedirectTo:redirect}});if(r.error&&/redirect url/i.test(r.error.message))r=await supabase.auth.signUp({email,password:$("apassword").value,options:{data:meta}});if(r.error)throw r.error;if(r.data.session)await bootstrap(r.data.user);$("authmsg").textContent="Account created. Complete email confirmation when required."}
 else {const redirect=location.href.split("#")[0];let r=await supabase.auth.resetPasswordForEmail(email,{redirectTo:redirect});if(r.error&&/redirect url/i.test(r.error.message))r=await supabase.auth.resetPasswordForEmail(email);if(r.error)throw r.error;$("authmsg").textContent="Password reset email requested."}
}catch(err){$("authmsg").textContent=err?.message||"Authentication failed."}};

async function bootstrap(user){const m=user?.user_metadata||{};const {data,error}=await supabase.rpc("v2_bootstrap_profile",{org_name:m.org_name||"ELITZE Organization",display_name:m.display_name||null});if(error)throw error;await loadProfile(data)}
async function loadProfile(){const {data,error}=await supabase.from("v2_profiles").select("organization_id,role,display_name").maybeSingle();if(error)throw error;profile=data}
async function loadConsole(){const {data}=await supabase.auth.getSession();const user=data.session?.user;const signed=!!user;$("console").classList.toggle("hidden",!signed);$("auth").textContent=signed?"Console":"Sign in";if(!signed)return;$("email").textContent=user.email||"Authenticated user";await loadProfile();if(!profile)return;const {data:org}=await supabase.from("v2_organizations").select("name").eq("id",profile.organization_id).maybeSingle();$("org").textContent=(org?.name||"Organization record")+" · "+profile.role;const {data:aal}=await supabase.auth.mfa.getAuthenticatorAssuranceLevel();$("aal").textContent=(aal?.currentLevel||"aal1").toUpperCase();await loadRequests();await loadMfa()}
async function loadRequests(){const {data,error}=await supabase.from("v2_security_requests").select("id,target,profile,status,evidence_state,created_at").order("created_at",{ascending:false}).limit(50);if(error)throw error;$("count").textContent=String(data?.length||0);$("requests").innerHTML=data?.length?data.map(r=>'<div class="request"><b>'+esc(r.target)+'</b><small>'+esc(r.profile)+" · "+esc(r.status)+" · evidence "+esc(r.evidence_state)+" · "+esc(new Date(r.created_at).toLocaleString())+"</small></div>").join(""):'<p class="muted">No requests recorded.</p>'}
const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function loadMfa(){const {data,error}=await supabase.auth.mfa.listFactors();if(error)return;const verified=(data?.totp||[]).filter(f=>f.status==="verified");$("mfastate").textContent=verified.length?"TOTP verified":"No verified TOTP factor";$("mfa").textContent=verified.length?"TOTP enabled":"Enable TOTP";$("mfa").disabled=!!verified.length}
$("mfa").onclick=async()=>{const {data,error}=await supabase.auth.mfa.enroll({factorType:"totp",friendlyName:"ELITZE V2 Authenticator"});if(error){$("mfastate").textContent=error.message;return}pendingFactor=data;$("qr").src=data.totp.qr_code;$("secret").textContent=data.totp.secret;$("mfaSetup").classList.remove("hidden");$("mfastate").textContent="Scan the code and enter a current authenticator code."}
$("mfaverify").onclick=async()=>{if(!pendingFactor)return;const {data:challenge,error:e1}=await supabase.auth.mfa.challenge({factorId:pendingFactor.id});if(e1){$("mfastate").textContent=e1.message;return}const {error:e2}=await supabase.auth.mfa.verify({factorId:pendingFactor.id,challengeId:challenge.id,code:$("code").value.trim()});if(e2){$("mfastate").textContent=e2.message;return}$("mfaSetup").classList.add("hidden");pendingFactor=null;await loadMfa()}
$("reqform").onsubmit=async e=>{e.preventDefault();const {data}=await supabase.auth.getSession();const user=data.session?.user;if(!user||!profile){$("reqresult").textContent="Authenticated organization required.";return}$("reqresult").textContent="Persisting request…";const {error}=await supabase.from("v2_security_requests").insert({organization_id:profile.organization_id,created_by:user.id,target:$("target").value.trim(),profile:$("profile").value});if(error){$("reqresult").textContent=error.message;return}$("reqresult").textContent="Request persisted. No scan has been claimed.";$("reqform").reset();await loadRequests()}
$("logout").onclick=async()=>{const {error}=await supabase.auth.signOut();if(error)$("authmsg").textContent=error.message;else await loadConsole()}

async function health(){try{const {data,error}=await supabase.rpc("v2_health_check");if(error)throw error;const row=data?.[0];$("db").textContent=row?.database_status==="PostgreSQL reachable"?"READY":"UNKNOWN";$("ah").textContent=row?.auth_provider==="Supabase Auth"?"READY":"UNKNOWN";$("healthnote").textContent="Live V2 backend checked at "+new Date(row?.checked_at||Date.now()).toLocaleString()+"."}catch(err){$("db").textContent="BLOCKED";$("ah").textContent="BLOCKED";$("healthnote").textContent="Live V2 health check failed: "+(err?.message||"unknown error")}}
supabase.auth.onAuthStateChange(()=>setTimeout(()=>loadConsole().catch(()=>{}),0)); health(); loadConsole().catch(()=>{});
