create extension if not exists pgcrypto;

create table if not exists public.v2_organizations(id uuid primary key default gen_random_uuid(),name text not null check(char_length(name) between 1 and 160),created_at timestamptz not null default now());
create table if not exists public.v2_profiles(user_id uuid primary key references auth.users(id) on delete cascade,organization_id uuid not null references public.v2_organizations(id) on delete cascade,role text not null default 'owner' check(role in('owner','admin','analyst','viewer')),display_name text,created_at timestamptz not null default now());
create table if not exists public.v2_security_requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.v2_organizations(id) on delete cascade,created_by uuid not null references auth.users(id) on delete restrict,target text not null check(char_length(target) between 1 and 500),profile text not null check(profile in('release-assurance','api-security','agent-security','mcp-security')),status text not null default 'REQUESTED' check(status in('REQUESTED','QUEUED','RUNNING','COMPLETED','BLOCKED')),evidence_state text not null default 'UNKNOWN' check(evidence_state in('OBSERVED','INFERRED','UNKNOWN','UNMEASURABLE')),created_at timestamptz not null default now());
create table if not exists public.v2_audit_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.v2_organizations(id) on delete cascade,actor_user_id uuid references auth.users(id) on delete set null,action text not null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create or replace function public.v2_my_org_id() returns uuid language sql stable security definer set search_path=public as $$ select organization_id from public.v2_profiles where user_id=auth.uid() $$;
create or replace function public.v2_bootstrap_profile(org_name text,display_name text default null) returns uuid language plpgsql security definer set search_path=public,auth as $$ declare uid uuid:=auth.uid(); org_id uuid; begin if uid is null then raise exception 'not_authenticated'; end if; if exists(select 1 from public.v2_profiles where user_id=uid) then return(select organization_id from public.v2_profiles where user_id=uid); end if; insert into public.v2_organizations(name) values(coalesce(nullif(trim(org_name),''),'ELITZE Organization')) returning id into org_id; insert into public.v2_profiles(user_id,organization_id,role,display_name) values(uid,org_id,'owner',nullif(trim(display_name),'')); insert into public.v2_audit_events(organization_id,actor_user_id,action) values(org_id,uid,'PROFILE_BOOTSTRAPPED'); return org_id; end; $$;
create or replace function public.v2_health_check() returns table(ok boolean,auth_provider text,database_status text,checked_at timestamptz) language sql stable security definer set search_path=public as $$ select true,'Supabase Auth','PostgreSQL reachable',now() $$;
alter table public.v2_organizations enable row level security;alter table public.v2_profiles enable row level security;alter table public.v2_security_requests enable row level security;alter table public.v2_audit_events enable row level security;
drop policy if exists org_read on public.v2_organizations;create policy org_read on public.v2_organizations for select to authenticated using(id=public.v2_my_org_id());
drop policy if exists profile_read on public.v2_profiles;create policy profile_read on public.v2_profiles for select to authenticated using(user_id=auth.uid());
drop policy if exists request_read on public.v2_security_requests;create policy request_read on public.v2_security_requests for select to authenticated using(organization_id=public.v2_my_org_id());
drop policy if exists request_insert on public.v2_security_requests;create policy request_insert on public.v2_security_requests for insert to authenticated with check(organization_id=public.v2_my_org_id() and created_by=auth.uid());
drop policy if exists audit_read on public.v2_audit_events;create policy audit_read on public.v2_audit_events for select to authenticated using(organization_id=public.v2_my_org_id());
grant execute on function public.v2_bootstrap_profile(text,text) to authenticated;grant execute on function public.v2_health_check() to anon,authenticated;grant select on public.v2_organizations,public.v2_profiles,public.v2_security_requests,public.v2_audit_events to authenticated;grant insert on public.v2_security_requests to authenticated;
